Perform\PageEditorBundle\Entity\Version:
    type: entity
    repositoryClass: Perform\PageEditorBundle\Repository\VersionRepository
    table: perform_page_editor_version
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        title:
            type: string
        page:
            type: string
        published:
            type: boolean
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        sections:
            targetEntity: Section
            mappedBy: version
            cascade:
                - 'persist'
                - 'remove'
