services:
    Perform\PageEditorBundle\Controller\:
        resource: '../../Controller'
        autowire: true
        autoconfigure: true

    Perform\PageEditorBundle\Command\:
        resource: '../../Command'
        autowire: true
        autoconfigure: true

    perform_page_editor.page_manager:
        class: Perform\PageEditorBundle\PageManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@twig"
            - "@perform_rich_content.renderer"

    perform_page_editor.session_manager:
        class: Perform\PageEditorBundle\SessionManager
        arguments:
            - "%perform_page_editor.toolbar.excluded_urls%"

    perform_page_editor.listener.page_manager:
        class: Perform\PageEditorBundle\EventListener\PageManagerListener
        arguments:
            - '@perform_page_editor.page_manager'
            - '@perform_page_editor.session_manager'
        tags:
            - {name: kernel.event_listener, event: kernel.request, priority: -128}
            - {name: kernel.event_listener, event: kernel.controller, priority: -128}

    perform_page_editor.listener.toolbar:
        class: Perform\PageEditorBundle\EventListener\ToolbarListener
        arguments:
            - '@perform_page_editor.page_manager'
            - "@twig"
        tags:
            # set priority to -99, just before the profiler listener, to make
            # sure resources used by the toolbar are included in the
            # profiler
            - {name: kernel.event_listener, event: kernel.response, priority: -99}

    perform_page_editor.menu.page_editor:
        class: Perform\PageEditorBundle\Menu\PageEditorLinkProvider
        tags:
            - {name: perform_base.link_provider, alias: page_editor}

    perform_page_editor.twig.content:
        class: Perform\PageEditorBundle\Twig\Extension\ContentExtension
        arguments:
            - '@perform_page_editor.page_manager'
        tags:
            - {name: twig.extension}

    perform_page_editor.repo.version:
        class: Perform\PageEditorBundle\Repository\VersionRepository
        factory:
            - "@doctrine.orm.entity_manager"
            - "getRepository"
        arguments:
            - "PerformPageEditorBundle:Version"

    Perform\PageEditorBundle\DataFixtures\ORM\LoadVersionData:
        class: Perform\PageEditorBundle\DataFixtures\ORM\LoadVersionData
        arguments:
            - "@perform_rich_content.fixture_manager"
            - "%perform_page_editor.fixture_definitions%"
